apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
    - image: amypyaephyonaing/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: amypyaephyonaing/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: amypyaephyonaing/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: amypyaephyonaing/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: amypyaephyonaing/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: amypyaephyonaing/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
manifests:
  rawYaml:
    - infra/k8s/k8s-dev/ingress-srv.yaml
    - infra/k8s/auth-depl.yaml
    - infra/k8s/expiration-redis-depl.yaml
    - infra/k8s/auth-mongo-depl.yaml
    - infra/k8s/ticket-mongo-depl.yaml
    - infra/k8s/orders-mongo-depl.yaml
    - infra/k8s/payment-mongo-depl.yaml
    - infra/k8s/client-depl.yaml
    - infra/k8s/ticket-depl.yaml
    - infra/k8s/nats-depl.yaml
    - infra/k8s/order-depl.yaml
    - infra/k8s/expiration-depl.yaml
    - infra/k8s/payment-depl.yaml