apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
    - image: amypyaephyonaing/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: amypyaephyonaing/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/ingress-srv.yaml
    - infra/k8s/auth-mongo-depl.yaml
    - infra/k8s/client-depl.yaml