apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
    - image: amypyaephyonaing/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/ingress-srv.yaml